[2023-12-01 00:34:48,971] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-12-01 00:37:10,857] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-12-01 00:37:11,549] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-12-01 00:37:23,201] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2023-12-01 00:37:23,201] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-12-01 00:37:28,926] 	INFO 	124 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-12-01 00:37:28,927] 	INFO 	131 	day_data.py 	<module>() 	Day Data Combined Started
[2023-12-01 00:37:40,671] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-12-01 00:37:41,430] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-12-01 00:38:34,854] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2023-12-01 00:38:34,854] 	INFO 	127 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-12-01 00:38:55,105] 	INFO 	194 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-12-01 00:38:55,105] 	INFO 	201 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-12-01 00:39:19,931] 	INFO 	231 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-12-01 00:39:20,725] 	INFO 	38 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-12-01 00:45:10,769] 	INFO 	146 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-12-01 00:45:11,556] 	INFO 	38 	fee_data.py 	<module>() 	Fee Data Started
[2023-12-01 00:46:39,581] 	ERROR 	137 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 429 Client Error: Too Many Requests for url: https://rpc.ankr.com/bsc
[2023-12-01 00:46:40,170] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-12-01 00:46:56,646] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-12-01 00:46:57,166] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2023-12-01 00:47:10,302] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2023-12-01 01:55:43,490] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-12-01 01:59:01,263] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-12-01 01:59:01,872] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-12-01 01:59:03,337] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2023-12-01 01:59:03,337] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-12-01 01:59:05,068] 	INFO 	124 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-12-01 01:59:05,068] 	INFO 	131 	day_data.py 	<module>() 	Day Data Combined Started
[2023-12-01 01:59:08,039] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-12-01 01:59:08,790] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-12-01 02:00:03,657] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2023-12-01 02:00:03,657] 	INFO 	127 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-12-01 02:00:25,414] 	INFO 	194 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-12-01 02:00:25,414] 	INFO 	201 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-12-01 02:00:43,608] 	INFO 	231 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-12-01 02:00:44,396] 	INFO 	38 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-12-01 02:08:55,598] 	INFO 	146 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-12-01 02:08:56,372] 	INFO 	38 	fee_data.py 	<module>() 	Fee Data Started
[2023-12-01 02:16:42,629] 	ERROR 	137 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-12-01 02:16:43,176] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-12-01 02:16:57,083] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-12-01 02:16:57,599] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2023-12-01 02:17:10,951] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2023-12-01 02:26:57,425] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-12-01 02:29:21,392] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-12-01 02:29:22,003] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-12-01 02:29:24,146] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2023-12-01 02:29:24,146] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-12-01 02:29:27,064] 	INFO 	124 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-12-01 02:29:27,064] 	INFO 	131 	day_data.py 	<module>() 	Day Data Combined Started
[2023-12-01 02:29:30,662] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-12-01 02:29:31,501] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-12-01 02:30:25,483] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2023-12-01 02:30:25,484] 	INFO 	127 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-12-01 02:30:47,506] 	INFO 	194 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-12-01 02:30:47,506] 	INFO 	201 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-12-01 02:31:27,982] 	INFO 	231 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-12-01 02:31:28,819] 	INFO 	38 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-12-01 02:37:28,608] 	INFO 	146 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-12-01 02:37:29,404] 	INFO 	38 	fee_data.py 	<module>() 	Fee Data Started
[2023-12-01 02:39:09,726] 	ERROR 	137 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 429 Client Error: Too Many Requests for url: https://rpc.ankr.com/bsc
[2023-12-01 02:39:10,280] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-12-01 02:39:26,251] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-12-01 02:39:26,785] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2023-12-01 02:39:36,114] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2023-12-01 03:07:48,454] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2023-12-01 03:10:54,704] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2023-12-01 03:10:55,401] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-12-01 03:10:58,487] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2023-12-01 03:10:58,487] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2023-12-01 03:11:00,722] 	INFO 	124 	day_data.py 	<module>() 	Day Data Fusion Ended
[2023-12-01 03:11:00,722] 	INFO 	131 	day_data.py 	<module>() 	Day Data Combined Started
[2023-12-01 03:11:03,429] 	INFO 	161 	day_data.py 	<module>() 	Day Data Combined Ended
[2023-12-01 03:11:04,234] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2023-12-01 03:11:57,966] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2023-12-01 03:11:57,966] 	INFO 	127 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2023-12-01 03:12:17,828] 	INFO 	194 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2023-12-01 03:12:17,828] 	INFO 	201 	pair_data.py 	<module>() 	Pair Data Combined Started
[2023-12-01 03:12:43,187] 	INFO 	231 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2023-12-01 03:12:43,974] 	INFO 	38 	bribe_data.py 	<module>() 	Bribe Data Started
[2023-12-01 03:20:31,609] 	INFO 	146 	bribe_data.py 	<module>() 	Bribe Data Ended
[2023-12-01 03:20:32,388] 	INFO 	38 	fee_data.py 	<module>() 	Fee Data Started
[2023-12-01 03:27:52,339] 	ERROR 	137 	fee_data.py 	<module>() 	Error occurred during Fee Data process. Error: 'address'
[2023-12-01 03:27:52,882] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2023-12-01 03:28:00,352] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2023-12-01 03:28:00,869] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2023-12-01 03:28:10,241] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
