[2025-09-01 01:19:50,882] 	INFO 	14 	id_data_v2.py 	<module>() 	ID Data Started
[2025-09-01 01:28:14,917] 	INFO 	163 	id_data_v2.py 	<module>() 	ID Data Ended
[2025-09-01 01:28:15,692] 	INFO 	14 	id_data_v3.py 	<module>() 	ID Data Started
[2025-09-01 01:28:16,326] 	ERROR 	44 	id_data_v3.py 	<module>() 	Error occurred during ID Data process. Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "id_data_v3.py", line 29, in <module>
    data = requests.get(url=fusion_api).json()['data']
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-09-01 01:28:16,919] 	INFO 	19 	day_data.py 	<module>() 	Day Data Started
[2025-09-01 01:28:19,676] 	ERROR 	69 	day_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-09-01 01:28:19,676] 	INFO 	80 	day_data.py 	<module>() 	Day Data Ended
[2025-09-01 01:28:19,676] 	INFO 	86 	day_data.py 	<module>() 	Day Data Fusion Started
[2025-09-01 01:28:22,788] 	ERROR 	145 	day_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-09-01 01:28:22,789] 	INFO 	156 	day_data.py 	<module>() 	Day Data Fusion Ended
[2025-09-01 01:28:22,789] 	INFO 	163 	day_data.py 	<module>() 	Day Data Combined Started
[2025-09-01 01:28:26,355] 	ERROR 	196 	day_data.py 	<module>() 	Data successfully added to Google Sheets.
[2025-09-01 01:28:26,355] 	INFO 	207 	day_data.py 	<module>() 	Day Data Combined Ended
[2025-09-01 01:28:27,210] 	INFO 	31 	pair_data.py 	<module>() 	Pair Data Started
[2025-09-01 01:29:57,939] 	ERROR 	108 	pair_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-09-01 01:29:57,939] 	INFO 	119 	pair_data.py 	<module>() 	Pair Data Ended
[2025-09-01 01:29:57,939] 	INFO 	136 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2025-09-01 01:29:58,581] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: auniBTC-FBTC, Address: 0xe2BB11d6b6A39e55762F5e14D632F0981198b3A7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:29:59,007] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:29:59,555] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aslpBNB-WBNB, Address: 0xda5BC174E3c122058Eb42465b78C7e1F639820A9, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:29:59,761] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: ajEUR-USDC, Address: 0x85B0533848E2a97069e2a5937fa927cA9133AF97, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:29:59,920] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: ajCHF-USDC, Address: 0x786C5B03C7A0a88A4cE6860a0D4aB2a1a0864e57, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:00,101] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aenzoBTC-ynBTCk, Address: 0x87BB1366C3d7AFc80bB0cEc7800FcE29D11AdBd7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:00,322] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-XVS, Address: 0x0748fb34bcb68d2c055cDfCb9F5bcB3549FcB456, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:00,438] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:00,754] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:00,948] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:01,637] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:01,923] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-DOLA, Address: 0xdB6BfF81311C5C4F72668D9C4c8a5E2CB4584A82, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:02,087] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWIF-WBNB, Address: 0x51Ea64A858B35eBF98DD40367cfcE2eFCb6B0373, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:03,088] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-STKBNB, Address: 0x84b78452A97C5afDa1400943333F691448069A29, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:04,072] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:04,566] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:04,753] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LPBNB, Address: 0x47600Bc3aE9b5b97ef92A55E550066944fE17670, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:04,858] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-KOMA, Address: 0x11f3c9CA27ed4931EFD0fbe0fd5DFC75157A1eA9, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:05,077] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-ERN, Address: 0xc609daA86FF43F34Eef52C468CbC4934eF8D2502, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:05,246] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-EDU, Address: 0x4bD39cfb05545c4238316dA69eCadA1b4CaABC05, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:05,438] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-DEUS, Address: 0x6a524C7328eb652248d1a3786f9DB0e74CA961F0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:05,641] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-COCO, Address: 0x58cAD2eA28853BBE1501188787C10469b2F0C4f1, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:06,392] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:07,014] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-USDV, Address: 0x739e561786C920D025d57eD99be5D4EcA3458E3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:07,801] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:08,788] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:08,979] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-DUSD, Address: 0xCf4cf048d0c754A71d559296aC1ccc9aeb0b25Be, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:09,222] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-BTE, Address: 0x9D49003383aB126C563ae2B7d545DB003e657F53, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:09,415] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDC-WUSDR, Address: 0xcbdE6C4f202eCc13267fD53913bc44B4Dd6eF998, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:10,260] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSTKBNB-THE, Address: 0xF1b7007694DBcba004DB73473CCa3c5aDd3803E4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:10,430] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSOLV-WBNB, Address: 0xBB59e13bD9B6Bf6f3E0421939649Fd47927d2206, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:10,958] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSFRXETH-FRXETH, Address: 0xd9e98A73102391b3D7d1D94C0c58541aBf99a14F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:12,104] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aPNP-WBNB, Address: 0x187784bC6812b056f4a54d84CDC98075F2d2eec6, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:12,278] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aORBS-WBNB, Address: 0x130348553b3dEA5d65767Dc390eFF257F9a9181d, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:12,468] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aOATH-ERN, Address: 0xDF5751BBEf0241878852253F8541A02c3Cbc2dd1, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:12,830] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aLVL-WBNB, Address: 0x011077b8199cAb999e895AED7f8A78755A678106, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:13,001] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aLTC-WBNB, Address: 0x320e85137bB10157BB8BBB22a912D516f8296cb5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:13,519] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aJBRL-USDC, Address: 0xd63bBA6078a328b93758Cc7556e21D3380397D41, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:13,636] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aID-WBNB, Address: 0xB66566fD115CAf17633504A5165a319F17D9F096, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:14,321] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:14,509] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:15,670] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-WBETH, Address: 0x3bc0Fc25aD4456cdd4e4805ED89Ec0d80Db5e2c4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:15,840] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-RDNT, Address: 0x403e786B4168eC718E2e6cB4FA874aaDE73D54f0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:16,019] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:16,359] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFAIR3-WBNB, Address: 0x0293b7F6B245C0160d0da4ea3b936569EcE5740c, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:16,724] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:17,448] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-STKBNB, Address: 0x8b41d72def3867E19f2285B45DA655e24928018F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:17,626] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-FRAX, Address: 0x82437aFe50B21d6910498706Dd4Fc7b6567e03eb, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:21,247] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:21,442] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBTCB-ynBTCk, Address: 0x94b3c0050e9111E955e3f3a48543bBF30Ba44BBC, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:21,778] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBTCB-FRAX, Address: 0xA4CF2A122e22BDDAEe91d9f3F086B07dCE5cf805, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:22,344] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-THE, Address: 0x1335Ffc90516b022425dBcFe4eA3610aA45f6C3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:22,705] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ETH, Address: 0x6B32E9178a6670dc9b19a74FE5080C54ea5347C7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:22,871] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:23,037] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-BTC, Address: 0x1a0a28D2217503f29f5579C16D8783bd7B9C8C93, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:23,759] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aARKEN-WBNB, Address: 0xCB995DaE5238c1e08C7289b335c80ED8d129A46b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:24,091] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:24,696] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-BTCB, Address: 0xE6BB969eE786E1a42C179EB11A5038640304Cb4C, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:24,821] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-ANKRETH, Address: 0xa31FDaD356065d3E244Ac33C2e7901Fff7e8AAec, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:26,003] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-8-THE a082, Address: 0x8929E532E551c82f5736aa18C78440691BC542D9, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:27,024] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-47-THE af58, Address: 0xDcc442489f861275B327D319534187592E193b36, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:27,363] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-43-THE 8423, Address: 0x6513127472979d0647c57BA1f4b6F06a73Ea963A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:27,521] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-41-THE CBDe, Address: 0xF8bED36dFB59E046716ecb89D87d19A28a636EC6, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:27,704] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-39-THE EB04, Address: 0x87a4276EaED3B46cb77ec41D6f6B9fC98B159725, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:27,883] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-37-THE F310, Address: 0xD688108301DF5D939bf272eb378429488a72eA52, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:28,150] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-36-THE Bc6a, Address: 0xFd60A2B164C86751Df65c8cf895F7b07e5A48C35, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:29,156] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-15-THE d198, Address: 0x7cEfCEa15158Df116534C75F2f677d4D1f077028, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:29,394] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-14-THE B802, Address: 0x8b8a362116f5F632B81e85e347846590bB4Be2A4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:29,568] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-11-THE 2ff5, Address: 0xe1Ad12B9f713710a8FFF593eB1c6E5F82d3C0b3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:29,738] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare E25c, Address: 0x52ddB7BD7CA73a20b6334cC08fCACa9906992a15, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:29,937] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare A2bB, Address: 0x9545d5399E50a8d9B9bE239BD7117b5655a9A45D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:30,105] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 638a, Address: 0xaB3790c5FaB8AFf0A41640Eb2c7b280289c657E5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:30,463] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 31eD, Address: 0x37CbdBb97C34ba577ADbFbB80b517cD6caB636E8, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-09-01 01:30:39,007] 	ERROR 	215 	pair_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-09-01 01:30:39,007] 	INFO 	226 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2025-09-01 01:30:39,007] 	INFO 	233 	pair_data.py 	<module>() 	Pair Data Combined Started
[2025-09-01 01:31:55,038] 	ERROR 	279 	pair_data.py 	<module>() 	Data successfully added to Google Sheets.
[2025-09-01 01:31:55,038] 	INFO 	290 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2025-09-01 01:31:55,990] 	INFO 	31 	bribe_data.py 	<module>() 	Bribe Data Started
[2025-09-01 01:31:59,080] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FITFI/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:01,057] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-liveThe/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:02,887] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:04,670] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/LIBERA: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:06,736] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aPNP-WBNB 07c3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:11,436] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aEQB-WBNB 982b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:13,368] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/MIX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:15,400] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DAO/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:17,176] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/ankrETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:19,269] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-ETH D728: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:23,364] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BUSD/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:24,918] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aKILO-WBNB 5aFa: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:26,680] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BTCB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:28,491] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 9287: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:30,291] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-MAI/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:34,211] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-eTHENA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:35,993] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DJED/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:37,766] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-6-THE BA13: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:39,538] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-cpTHE/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:41,290] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare Ea85: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:43,049] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-ETH 2e3d: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:47,718] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-11-THE 2ff5: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:49,628] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for ajEUR-USDC b314: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:51,396] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IDIA/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:53,202] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MAI/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:55,519] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BUSD/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:32:57,021] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-OATH/LQDR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:01,740] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-15-THE d198: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:03,645] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare a373: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:05,443] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HBR/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:07,562] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDAO-ankrBNB 9b0F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:09,881] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-WBNB 0252: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:12,701] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FITFI/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:14,453] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/USD+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:16,233] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:17,716] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-AST 3459: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:19,484] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aankrBNB-XVS 33f4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:21,768] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aTWT-ANKRBNB B039: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:25,705] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-FLOKI FC3e: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:27,646] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDAO-BUSD 988B: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:29,488] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BKN/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:31,255] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-BTC 5f88: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:33,588] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MATIC/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:35,373] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FRAX/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:39,498] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:41,676] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-PENDLE 76c9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:43,459] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-GHNY/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:45,367] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-MAI/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:48,219] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/BUSD OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:52,367] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-18-THE 960e: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:54,480] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-TWT/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:56,257] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aLISUSD-CHEEMS E491: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:33:58,483] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-FRXETH 02b3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:00,504] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-GRAIN/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:02,884] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XRP/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:04,698] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PSTAKE/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:06,480] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/ETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:08,520] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aLTC-WBNB 531d: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:10,306] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aGHNY-WBNB f892: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:12,080] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-BR CddB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:16,398] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for astERN-ERN d9F9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:18,854] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-THE DCDc: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:20,885] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:22,650] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWoD-WBNB 00B1: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:24,501] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for auniBTC-BTCB 5E0a: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:28,931] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-DEUS eCF4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:30,824] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFIL-ANKRBNB 356A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:32,867] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-RDNT 0CC5: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:34,887] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aXCAD-WBNB f2BC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:36,676] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BTCB/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:38,442] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 1E70: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:42,686] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-RDNT 97e8: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:45,333] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETH/frxETH 9452: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:47,587] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aEQB-FRXETH 0621: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:49,592] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 6613: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:51,082] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:52,578] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-38-THE E62E: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:55,543] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSFRXETH-FRXETH 2C3A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:57,797] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-ANKR eE80: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:34:59,795] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWEETH-ETH 0D39: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:01,874] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aTWT-WBNB 0749: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:03,627] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for auniBTC-FBTC e40b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:07,719] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-WBETH 308D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:10,141] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDV/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:11,870] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-QUO/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:13,636] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:15,369] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/liveThe: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:17,124] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-FRAX 1070: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:21,934] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-frxETH/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:24,307] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/USDC-jCHF-120-vLP: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:26,038] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFAIR3-WBNB 8D29: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:27,774] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSTKBNB-THE 78AF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:29,517] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/CHAM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:31,474] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDAO-ankrBNB 0fB0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:34,735] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/MIX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:36,446] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-CHAM/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:38,171] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aXCAD-WBNB 376F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:39,887] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-GHNY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:41,648] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/rBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:43,617] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-MATIC 4f66: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:47,819] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aID-ANKRBNB 32c6: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:49,941] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:51,428] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-AVAX/CHAM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:53,392] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-UNW/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:55,114] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:35:56,586] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-COCO effD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:01,310] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-sfrxETH/frxETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:03,686] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-RDNT 6f46: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:05,905] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-34-THE D089: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:07,933] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-TAROT/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:09,657] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-FRAX/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:13,156] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBTCB-STKBNB 51b5: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:15,114] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:16,815] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-TAROT/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:18,500] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/XCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:20,464] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aJBRL-USDC 00FC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:22,184] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:25,464] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-30-THE e5c9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:27,342] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/USD+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:29,304] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HBR/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:30,982] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-7-THE deb0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:32,663] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:34,607] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-WBNB 7677: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:38,863] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/SD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:40,923] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-46-THE d0DF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:43,110] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BTCB/XCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:45,071] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USD+/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:47,065] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCASH-USDT 5587: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:51,850] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/ANKR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:53,707] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DAI/MAI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:56,134] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDC/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:58,071] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-cpTHENA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:36:59,791] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-LIBERA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:01,508] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-14-THE B802: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:05,260] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aTWT-WBNB 5196: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:07,156] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:09,164] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-39-THE EB04: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:10,888] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/BTCB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:12,874] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-THE b15b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:14,400] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/multiBTC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:18,387] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-GHNY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:20,245] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/XCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:21,936] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for asolvBTC-BTCB 0995: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:24,228] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDV/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:25,993] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-OATH/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:30,663] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-BLOCK 5DD2: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:32,560] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-13-THE Dbe6: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:34,346] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BTCB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:36,148] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-CGPT/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:37,977] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FRAX/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:42,243] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/ankrBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:44,425] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FEAR/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:46,248] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSOLV-WBNB 62fb: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:48,042] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/liveThe: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:49,837] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-fBOMB/liveThe: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:52,832] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETS Alpha/USD+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:54,916] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/MGP: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:56,675] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MIX/MATIC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:37:58,696] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSINGULARRY-WBNB 9A37: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:00,469] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-uniBTC/brBTC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:02,510] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PERRY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:06,628] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANDY-WBNB B254: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:08,570] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-12-THE 2367: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:10,366] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWIF-WBNB 067F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:12,178] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFIL-WBNB 19B5: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:13,980] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCSIX-USDT 458D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:17,855] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MPX/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:19,768] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-C98/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:21,769] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/MATIC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:23,535] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-sfrxETH/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:25,557] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBTCB-FRAX 3CAE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:30,266] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-FRAX b48b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:32,944] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/WBNB OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:34,731] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrMATIC/MATIC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:36,719] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-9-THE 3fd0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:38,499] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/MGP: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:42,915] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-42-THE d5bb: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:45,616] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/BTCB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:47,611] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-LPBNB Ba2b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:49,412] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/FITFI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:51,200] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-DOLA/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:54,442] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/JARVIS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:56,482] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aynBNBx-WBNB 7e0F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:38:58,243] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BTCB/Bridged mBTC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:00,811] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-47-THE af58: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:02,977] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-OVN/USDT+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:07,311] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-wstETH bEcD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:09,451] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MULTI/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:11,248] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aslpBNB-WBNB acCd: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:13,080] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/PRIMAL: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:14,938] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-FRAX/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:19,447] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/GHNY: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:21,433] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-22-THE 0053: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:23,226] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DUSD/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:25,550] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:27,061] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-24-THE 9302: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:31,630] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-27-THE fEa0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:33,761] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-19-THE 6683: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:35,839] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-36-THE Bc6a: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:37,623] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-29-THE f060: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:39,386] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/XCAD OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:42,532] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/ANKR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:44,592] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PION/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:46,380] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MAI/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:48,403] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-sUSDa/USDa: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:50,447] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/BIFI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:54,236] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-32-THE 3357: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:56,324] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DOLA/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:58,317] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDC/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:39:59,779] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-33-THE 025d: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:01,764] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-fBOMB/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:03,591] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-LQDR 0D12: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:07,446] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:09,562] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aGRAIN-WBNB EAD0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:11,474] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-45-THE 1B9C: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:14,112] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-qTHE/QUO: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:16,259] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-THE 1aCB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:20,422] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-Bridged mwBETH/wBETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:23,550] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-EDU 6feA: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:25,367] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-WBNB/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:26,961] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/USDC OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:28,792] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ABOND/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:32,954] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/PLAY: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:34,898] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-20-THE 93b2: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:37,157] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETS Alpha/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:38,979] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/ankrETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:41,066] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BUSD/SLM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:43,931] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/CHAM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:45,783] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:47,558] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT+/USD+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:49,887] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/HBR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:51,946] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/FTM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:53,746] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-WBNB e947: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:57,944] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/PLAY: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:40:59,744] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aAITECH-WBNB 27B6: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:01,602] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IPAD/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:03,461] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ID/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:05,170] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-fBOMB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:07,096] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/frxETH d25C: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:11,760] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DOLA/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:14,288] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MAI/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:16,321] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-JRT/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:18,144] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/ankrMATIC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:20,169] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:23,262] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MULTI/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:25,185] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/AST: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:26,986] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-DAO/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:28,863] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FIL/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:30,679] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-AVAX/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:32,444] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-stkBNB/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:36,030] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/LIQ: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:38,085] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/stkBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:39,954] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:41,774] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:43,663] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-wUSDR/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:45,464] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-XVS eE7D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:49,732] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBTCB-ynBTCk CC09: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:52,237] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aPUFFER-WBNB 6b64: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:54,031] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:55,888] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/OATH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:41:57,683] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:01,828] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBANK-WBNB D313: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:03,690] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/PRIMAL: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:05,500] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/LINK: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:07,571] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FS/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:09,438] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/dXCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:11,203] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/dXCAD OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:15,220] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/THE OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:17,050] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BUSD/SLM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:18,958] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:20,507] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/NFTB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:22,406] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BETS/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:24,467] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/LIQ: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:28,529] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-THE 3f3C: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:30,097] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-MATIC 1E3F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:31,877] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FS/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:33,707] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-FRAX/sFRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:36,087] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-STKBNB 668C: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:40,519] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/TAROT 8A8b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:42,556] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-wUSDR/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:44,411] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:46,020] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MIX/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:47,868] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FS/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:49,746] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FEAR/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:53,891] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSnBNB-WBNB 6708: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:56,311] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/USDT OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:42:58,126] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-jBRL/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:00,009] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-PLAY B74d: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:01,969] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aankrBNB-DUSD 87b1: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:05,630] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-ERN 67D3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:07,660] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:09,441] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-NGL/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:11,213] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-LQDR/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:12,981] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USD+/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:14,747] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IDIA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:18,829] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-DAO/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:20,740] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/LQDR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:22,578] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/BTCB OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:24,711] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:26,508] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-jBRL/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:30,746] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-43-THE 8423: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:33,431] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/KOL: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:35,466] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/LIQ: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:37,254] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FTM/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:38,990] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IDIA/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:42,724] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:45,421] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IDIA/C98: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:47,478] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-LIBERA/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:49,166] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-WBNB/BIFI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:50,858] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/ANKR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:54,324] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-THE/FLOKI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:56,074] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USD+/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:57,775] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BTCB/multiBTC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:43:59,729] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-cpTHENA/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:01,467] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/PLAY: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:03,494] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PLAY/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:07,673] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:10,354] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/TAROT 7086: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:12,421] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/IPAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:14,186] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ABOND/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:16,005] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/SEF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:20,233] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-xZOOMER/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:22,128] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/TTM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:23,898] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETH/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:25,656] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-Cake/mCake: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:28,544] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT/USDa: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:33,142] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PREON/STAR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:35,278] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/$AIAGENT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:37,125] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-31-THE 1Cb3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:39,194] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-35-THE 5736: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:41,295] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-41-THE CBDe: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:45,433] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-WBNB 755b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:47,243] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFTM-WBNB 6e6B: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:49,084] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCGPT-BUSD 68C0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:50,854] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFTM-WBNB 4Fee: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:52,617] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCGPT-BUSD 4536: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:54,393] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-RDNT 5420: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:44:59,344] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-FLOKI EF58: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:01,220] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-LQDR 3DCD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:03,004] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDOGE-WBNB F0cF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:04,792] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aOKSE-WBNB 1191: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:06,573] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-THE 1Ef3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:08,063] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-USDT 6071: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:12,223] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aMULTI-WBNB 7103: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:14,099] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-ANKR b548: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:15,932] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-FRAX 6e92: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:18,580] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDAO-BUSD d6ea: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:20,398] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aMULTI-WBNB D6f4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:23,358] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-ANKRETH 33e9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:25,725] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-ANKR 0808: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:27,654] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-OATH d561: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:29,479] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aLTC-WBNB 0C62: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:31,316] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-ANKR C1be: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:36,161] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-USDT 3aBD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:38,337] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-OATH e2b4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:40,166] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aXCAD-BUSD E405: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:42,001] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-FRXETH A888: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:44,104] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-XCAD A245: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:48,512] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-FRAX A59c: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:51,028] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-THE 1A05: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:53,010] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-FRAX 759D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:45:55,524] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-WBNB 0F68: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:00,529] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSTKBNB-THE 27D7: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:02,513] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-BTE 5bc0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:04,323] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-BTE 221c: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:06,134] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-THE 4a5f: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:08,214] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-BIFI 2aBc: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:12,521] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-LINK 587A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:14,889] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-BTCB 7be8: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:17,121] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRAX-ERN 18ab: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:19,900] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aERN-OATH 4A7D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:22,996] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aLVL-WBNB E6EE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:24,735] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-STKBNB 7ea9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:26,717] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-ERN 578A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:28,944] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aARKEN-WBNB 44D0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:30,658] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aEQB-WBNB B32f: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:32,396] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-PENDLE eCD0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:36,342] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-OOE C8C3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:38,256] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aEQB-FRXETH B098: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:40,595] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aAXLLQDR-WBNB e1ce: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:42,328] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-STKBNB 0537: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:44,305] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-OOE 1974: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:48,392] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-WBNB e7a9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:50,445] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCSIX-USDT 9a14: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:52,161] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-RDNT a427: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:54,377] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aAXLLQDR-WBNB Aa30: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:46:56,114] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-WBNB 9cfd: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:01,349] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aOATH-ERN 75df: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:03,451] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDC-WUSDR 9891: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:05,156] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aAITECH-WBNB E8d7: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:06,863] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aankrBNB-DUSD b1f9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:08,810] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-DUSD 88ab: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:10,526] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aOATH-ERN 2F85: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:26,738] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-AST 11a9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:28,467] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSOL-WBNB eBFD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:30,208] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aTOKEN-WBNB d726: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:32,222] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-BTCB fc90: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:34,224] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for asolvBTC-WBNB B1C6: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:37,865] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-USDV 9FEf: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:40,007] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-inwbETH Be13: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:41,974] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-LISTA ff22: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:43,944] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aORBS-WBNB bA1A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:45,616] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCAT-WBNB 51cc: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:49,981] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aZRO-WBNB 98Eb: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:51,751] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-RWA 4aAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:53,425] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for ajCHF-USDC 4657: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:55,080] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aMONKY-WBNB Cd00: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:56,753] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-SDM 152E: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:47:58,485] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-8-THE a082: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:03,997] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-23-THE c02E: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:05,824] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-44-THE Bc06: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:08,305] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 6055: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:09,995] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-26-THE 2c1f: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:11,695] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-28-THE 4C61: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:13,644] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 50e8: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:17,459] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare A2bB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:19,319] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 3E21: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:21,004] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 31eD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:22,673] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 638a: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:24,375] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare E25c: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:26,068] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare a32e: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:30,525] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare f360: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-09-01 01:48:32,500] 	ERROR 	150 	bribe_data.py 	<module>() 	Error occurred during Bribe Data process. Error: Dataframe is empty
[2025-09-01 01:48:33,111] 	INFO 	17 	revenue_data.py 	<module>() 	Revenue Data Started
[2025-09-01 01:48:43,739] 	ERROR 	94 	revenue_data.py 	<module>() 	Error occurred during Revenue Data process. Error: 'int' object has no attribute 'startswith'
[2025-09-01 01:48:44,338] 	INFO 	16 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2025-09-01 01:48:51,462] 	ERROR 	96 	revenue_data_v2.py 	<module>() 	Error occurred during Revenue Data process. Error: 'float' object has no attribute 'startswith'
[2025-09-01 01:48:52,055] 	INFO 	29 	tvl_data.py 	<module>() 	TVL Data Started
[2025-09-01 01:48:52,120] 	INFO 	33 	tvl_data.py 	<module>() 	Response status code: 403
[2025-09-01 01:48:52,120] 	INFO 	34 	tvl_data.py 	<module>() 	Response content: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta nam
[2025-09-01 01:48:52,120] 	ERROR 	95 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tvl_data.py", line 35, in <module>
    ids_df = pd.json_normalize(response.json()['data'])[['symbol', 'type', 'address']]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-09-01 01:48:52,121] 	INFO 	108 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2025-09-01 01:48:52,171] 	ERROR 	182 	tvl_data.py 	<module>() 	Error occurred during TVL Data Fusion process. Error: name 'ids_df' is not defined
Traceback (most recent call last):
  File "tvl_data.py", line 115, in <module>
    ids_cl_df = ids_df[(ids_df['type'] != 'Volatile') & (ids_df['type'] != 'Stable')]
NameError: name 'ids_df' is not defined
[2025-09-01 01:48:52,171] 	INFO 	187 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2025-09-01 01:48:52,171] 	ERROR 	248 	tvl_data.py 	<module>() 	Error occurred during TVL Data Combined process. Error: name 'v1_df' is not defined
Traceback (most recent call last):
  File "tvl_data.py", line 190, in <module>
    tvl_df = pd.concat([v1_df, cl_df], ignore_index=True)
NameError: name 'v1_df' is not defined
[2025-09-01 01:48:52,840] 	INFO 	27 	fee_tvl_data.py 	<module>() 	Fee TVL Data Started
[2025-09-01 01:49:01,234] 	ERROR 	66 	fee_tvl_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-09-01 01:49:01,234] 	INFO 	77 	fee_tvl_data.py 	<module>() 	Fee TVL Data Ended
