[2025-08-01 01:27:47,293] 	INFO 	14 	id_data_v2.py 	<module>() 	ID Data Started
[2025-08-01 01:37:57,513] 	INFO 	163 	id_data_v2.py 	<module>() 	ID Data Ended
[2025-08-01 01:37:58,306] 	INFO 	14 	id_data_v3.py 	<module>() 	ID Data Started
[2025-08-01 01:37:58,617] 	ERROR 	44 	id_data_v3.py 	<module>() 	Error occurred during ID Data process. Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "id_data_v3.py", line 29, in <module>
    data = requests.get(url=fusion_api).json()['data']
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-08-01 01:37:59,235] 	INFO 	19 	day_data.py 	<module>() 	Day Data Started
[2025-08-01 01:38:02,489] 	ERROR 	69 	day_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-08-01 01:38:02,489] 	INFO 	80 	day_data.py 	<module>() 	Day Data Ended
[2025-08-01 01:38:02,489] 	INFO 	86 	day_data.py 	<module>() 	Day Data Fusion Started
[2025-08-01 01:38:05,046] 	ERROR 	145 	day_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-08-01 01:38:05,046] 	INFO 	156 	day_data.py 	<module>() 	Day Data Fusion Ended
[2025-08-01 01:38:05,046] 	INFO 	163 	day_data.py 	<module>() 	Day Data Combined Started
[2025-08-01 01:38:08,562] 	ERROR 	196 	day_data.py 	<module>() 	Data successfully added to Google Sheets.
[2025-08-01 01:38:08,562] 	INFO 	207 	day_data.py 	<module>() 	Day Data Combined Ended
[2025-08-01 01:38:09,419] 	INFO 	31 	pair_data.py 	<module>() 	Pair Data Started
[2025-08-01 01:40:03,817] 	ERROR 	108 	pair_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-08-01 01:40:03,817] 	INFO 	119 	pair_data.py 	<module>() 	Pair Data Ended
[2025-08-01 01:40:03,817] 	INFO 	136 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2025-08-01 01:40:04,114] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aynBNBx-WBNB, Address: 0xcdEDb4bAd9978E1d0A82Ad2061D0345f48014bc4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:04,477] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: auniBTC-FBTC, Address: 0xe2BB11d6b6A39e55762F5e14D632F0981198b3A7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:04,951] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:05,549] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aslpBNB-WBNB, Address: 0xda5BC174E3c122058Eb42465b78C7e1F639820A9, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:05,732] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: ajEUR-USDC, Address: 0x85B0533848E2a97069e2a5937fa927cA9133AF97, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:05,988] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: ajCHF-USDC, Address: 0x786C5B03C7A0a88A4cE6860a0D4aB2a1a0864e57, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:06,256] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aenzoBTC-ynBTCk, Address: 0x87BB1366C3d7AFc80bB0cEc7800FcE29D11AdBd7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:06,476] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-XVS, Address: 0x0748fb34bcb68d2c055cDfCb9F5bcB3549FcB456, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:06,729] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:07,254] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:07,433] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:07,853] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:10,130] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:10,610] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:10,824] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LPBNB, Address: 0x47600Bc3aE9b5b97ef92A55E550066944fE17670, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:11,207] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-ERN, Address: 0xc609daA86FF43F34Eef52C468CbC4934eF8D2502, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:11,388] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-EDU, Address: 0x4bD39cfb05545c4238316dA69eCadA1b4CaABC05, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:11,841] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-COCO, Address: 0x58cAD2eA28853BBE1501188787C10469b2F0C4f1, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:12,466] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:13,157] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-USDV, Address: 0x739e561786C920D025d57eD99be5D4EcA3458E3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:15,030] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:15,199] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-DUSD, Address: 0xCf4cf048d0c754A71d559296aC1ccc9aeb0b25Be, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:15,541] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDC-WUSDR, Address: 0xcbdE6C4f202eCc13267fD53913bc44B4Dd6eF998, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:16,319] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSTKBNB-THE, Address: 0xF1b7007694DBcba004DB73473CCa3c5aDd3803E4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:16,483] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSOLV-WBNB, Address: 0xBB59e13bD9B6Bf6f3E0421939649Fd47927d2206, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:17,111] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSFRXETH-FRXETH, Address: 0xd9e98A73102391b3D7d1D94C0c58541aBf99a14F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:17,444] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aPNP-WBNB, Address: 0x187784bC6812b056f4a54d84CDC98075F2d2eec6, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:17,685] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aORBS-WBNB, Address: 0x130348553b3dEA5d65767Dc390eFF257F9a9181d, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:17,890] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aOATH-ERN, Address: 0xDF5751BBEf0241878852253F8541A02c3Cbc2dd1, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:18,275] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aLVL-WBNB, Address: 0x011077b8199cAb999e895AED7f8A78755A678106, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:18,940] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aJBRL-USDC, Address: 0xd63bBA6078a328b93758Cc7556e21D3380397D41, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:19,110] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aID-WBNB, Address: 0xB66566fD115CAf17633504A5165a319F17D9F096, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:19,916] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:20,119] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:20,638] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-WBETH, Address: 0x3bc0Fc25aD4456cdd4e4805ED89Ec0d80Db5e2c4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:20,823] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-RDNT, Address: 0x403e786B4168eC718E2e6cB4FA874aaDE73D54f0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:20,984] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:21,411] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFAIR3-WBNB, Address: 0x0293b7F6B245C0160d0da4ea3b936569EcE5740c, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:21,808] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:22,621] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-STKBNB, Address: 0x8b41d72def3867E19f2285B45DA655e24928018F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:24,671] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:24,910] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBTCB-ynBTCk, Address: 0x94b3c0050e9111E955e3f3a48543bBF30Ba44BBC, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:25,889] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-THE, Address: 0x1335Ffc90516b022425dBcFe4eA3610aA45f6C3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:26,421] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:27,403] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aARKEN-WBNB, Address: 0xCB995DaE5238c1e08C7289b335c80ED8d129A46b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:28,661] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-ANKRETH, Address: 0xa31FDaD356065d3E244Ac33C2e7901Fff7e8AAec, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:28,821] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-ANKR, Address: 0xC8Cbf9b12552c0B85fc368AA530cc31E00526E2F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:29,585] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-8-THE a082, Address: 0x8929E532E551c82f5736aa18C78440691BC542D9, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:30,337] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-47-THE af58, Address: 0xDcc442489f861275B327D319534187592E193b36, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:30,897] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-41-THE CBDe, Address: 0xF8bED36dFB59E046716ecb89D87d19A28a636EC6, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:31,070] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-39-THE EB04, Address: 0x87a4276EaED3B46cb77ec41D6f6B9fC98B159725, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:31,278] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-37-THE F310, Address: 0xD688108301DF5D939bf272eb378429488a72eA52, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:31,471] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-36-THE Bc6a, Address: 0xFd60A2B164C86751Df65c8cf895F7b07e5A48C35, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:32,319] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-15-THE d198, Address: 0x7cEfCEa15158Df116534C75F2f677d4D1f077028, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:32,496] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-14-THE B802, Address: 0x8b8a362116f5F632B81e85e347846590bB4Be2A4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:32,666] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-11-THE 2ff5, Address: 0xe1Ad12B9f713710a8FFF593eB1c6E5F82d3C0b3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:32,826] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare E25c, Address: 0x52ddB7BD7CA73a20b6334cC08fCACa9906992a15, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:32,997] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare A2bB, Address: 0x9545d5399E50a8d9B9bE239BD7117b5655a9A45D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:33,200] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 638a, Address: 0xaB3790c5FaB8AFf0A41640Eb2c7b280289c657E5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:33,576] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 31eD, Address: 0x37CbdBb97C34ba577ADbFbB80b517cD6caB636E8, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-08-01 01:40:43,439] 	ERROR 	215 	pair_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-08-01 01:40:43,440] 	INFO 	226 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2025-08-01 01:40:43,440] 	INFO 	233 	pair_data.py 	<module>() 	Pair Data Combined Started
[2025-08-01 01:42:02,941] 	ERROR 	279 	pair_data.py 	<module>() 	Data successfully added to Google Sheets.
[2025-08-01 01:42:02,941] 	INFO 	290 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2025-08-01 01:42:03,887] 	INFO 	31 	bribe_data.py 	<module>() 	Bribe Data Started
[2025-08-01 01:42:07,166] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FITFI/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:09,909] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-liveThe/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:12,344] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:14,781] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/LIBERA: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:21,074] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-THE C5be: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:23,866] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aEQB-WBNB 982b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:26,130] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/MIX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:28,797] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DAO/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:32,996] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-ETH D728: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:36,136] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-5-THE 740b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:38,519] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BUSD/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:40,572] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aKILO-WBNB 5aFa: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:44,566] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 9287: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:46,891] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-MAI/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:49,876] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aGRAIN-WBNB 6BC7: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:52,209] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-eTHENA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:56,733] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-6-THE BA13: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:42:59,117] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-cpTHE/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:01,409] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare Ea85: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:03,738] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-ETH 2e3d: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:09,717] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for ajEUR-USDC b314: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:12,396] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IDIA/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:14,984] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MAI/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:18,361] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BUSD/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:24,908] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-RBNB 5772: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:27,722] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-15-THE d198: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:30,157] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare a373: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:32,616] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HBR/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:36,916] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-WBNB 0252: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:39,283] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-DOGE/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:41,718] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FITFI/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:44,004] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/USD+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:51,048] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aankrBNB-XVS 33f4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:54,188] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aTWT-ANKRBNB B039: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:43:56,825] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/DEUS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:02,547] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BKN/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:04,896] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-BTC 5f88: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:07,779] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MATIC/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:10,024] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FRAX/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:14,315] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:16,854] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:19,626] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-PENDLE 76c9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:22,021] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-GHNY/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:37,676] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/BUSD OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:40,196] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-ERN f047: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:43,613] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-18-THE 960e: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:46,354] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-TWT/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:52,751] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-GRAIN/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:55,214] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XRP/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:57,540] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PSTAKE/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:44:59,945] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/ETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:06,509] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aGHNY-WBNB f892: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:08,910] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-BR CddB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:11,141] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aXCAD-BUSD 3613: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:13,433] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-C98/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:18,374] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-THE DCDc: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:21,075] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:23,367] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWoD-WBNB 00B1: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:25,619] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for auniBTC-BTCB 5E0a: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:31,296] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFIL-ANKRBNB 356A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:33,996] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-RDNT 0CC5: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:36,632] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aXCAD-WBNB f2BC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:38,919] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BTCB/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:43,369] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDC/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:45,515] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aPNP-WBNB C4FF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:47,906] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-RDNT 97e8: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:50,909] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETH/frxETH 9452: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:56,019] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 6613: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:45:58,084] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:00,056] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-38-THE E62E: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:02,403] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSFRXETH-FRXETH 2C3A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:11,133] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aTWT-WBNB 0749: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:13,530] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for auniBTC-FBTC e40b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:16,489] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBTCB-WBNB 4D3F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:18,950] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-WBETH 308D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:24,663] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:27,061] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/liveThe: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:29,471] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-FRAX 1070: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:32,709] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aenzoBTC-ynBTCk Af96: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:42,909] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFAIR3-WBNB 8D29: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:45,482] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSTKBNB-THE 78AF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:47,882] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/CHAM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:50,758] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDAO-ankrBNB 0fB0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:55,948] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/MIX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:46:58,465] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-CHAM/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:00,937] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aXCAD-WBNB 376F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:03,470] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-GHNY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:09,389] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-FRXETH 275E: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:12,635] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aID-ANKRBNB 32c6: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:15,356] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:17,437] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-AVAX/CHAM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:24,638] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-COCO effD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:27,028] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-mPendle/PENDLE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:30,359] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETH/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:32,768] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-sfrxETH/frxETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:39,100] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-34-THE D089: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:41,883] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-TAROT/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:44,340] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-FRAX/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:47,079] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-cpTHE/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:53,593] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-TAROT/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:56,188] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/XCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:47:58,979] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aJBRL-USDC 00FC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:01,719] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:09,045] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/USD+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:11,918] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HBR/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:14,333] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-7-THE deb0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:16,729] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:22,773] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-AICELL 0Dbb: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:25,218] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/SD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:28,064] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-46-THE d0DF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:31,157] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BTCB/XCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:36,881] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCASH-USDT 5587: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:39,696] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-inETH 4f02: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:42,538] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-USDT 3e64: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:45,027] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/ANKR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:51,318] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDC/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:54,332] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-cpTHENA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:56,844] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-LIBERA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:48:59,420] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-14-THE B802: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:05,382] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aTWT-WBNB 5196: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:07,842] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:10,603] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-39-THE EB04: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:13,046] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/BTCB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:22,357] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FEAR/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:24,830] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFIL-WBNB 0836: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:27,107] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-GHNY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:29,450] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/XCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:33,412] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDV/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:35,682] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-OATH/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:37,914] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-WBNB CDA2: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:39,874] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MAI/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:44,996] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-13-THE Dbe6: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:47,652] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BTCB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:50,187] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-CGPT/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:52,680] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FRAX/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:49:57,702] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/ankrBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:00,639] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FEAR/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:03,123] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSOLV-WBNB 62fb: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:05,621] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/liveThe: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:16,512] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/MGP: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:19,149] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MIX/MATIC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:21,992] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSINGULARRY-WBNB 9A37: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:24,484] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-uniBTC/brBTC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:31,553] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HBR/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:34,412] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANDY-WBNB B254: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:36,818] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-12-THE 2367: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:39,146] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWIF-WBNB 067F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:44,430] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCSIX-USDT 458D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:46,819] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-16-THE D6c9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:49,381] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MPX/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:51,639] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-C98/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:50:59,975] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBTCB-FRAX 3CAE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:03,114] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-25-THE d02E: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:05,878] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ankrBNB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:08,245] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-FRAX b48b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:19,197] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-9-THE 3fd0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:21,685] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/MGP: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:24,107] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-CaptainBNB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:26,532] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-42-THE d5bb: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:32,998] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/FITFI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:35,512] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-DOLA/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:38,217] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/JARVIS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:40,904] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aynBNBx-WBNB 7e0F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:44,318] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BTCB/Bridged mBTC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:47,677] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-47-THE af58: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:50,455] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-OVN/USDT+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:53,158] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/MGP: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:51:58,095] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aslpBNB-WBNB acCd: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:00,479] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/PRIMAL: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:02,750] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-FRAX/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:05,303] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-DEUS 03CA: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:07,626] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-FDUSD C4F3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:12,372] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DUSD/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:15,452] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:17,404] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-24-THE 9302: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:20,042] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-jBRL/BRZ: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:23,710] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-KOMA 78E4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:26,003] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-27-THE fEa0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:28,632] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-19-THE 6683: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:31,232] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-36-THE Bc6a: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:35,765] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/XCAD OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:38,659] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aID-WBNB E753: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:41,038] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/ANKR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:43,825] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PION/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:52:59,595] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/BIFI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:02,076] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-17-THE Fc8C: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:05,111] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-32-THE 3357: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:07,848] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DOLA/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:14,706] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-fBOMB/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:17,120] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-LQDR 0D12: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:19,413] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-37-THE F310: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:21,971] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:27,059] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-45-THE 1B9C: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:30,462] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-qTHE/QUO: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:33,096] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-THE 1aCB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:35,146] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PRIMAL/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:44,010] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-EDU 6feA: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:46,344] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-WBNB/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:48,258] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/USDC OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:50,499] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ABOND/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:53:52,738] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/SLM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:54:11,313] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-20-THE 93b2: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:54:14,103] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETS Alpha/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:54:16,539] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/ankrETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:54:19,171] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BUSD/SLM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:54:40,351] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/HBR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:54:43,322] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/FTM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:54:45,718] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-WBNB e947: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:54:48,151] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:54:54,833] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aAITECH-WBNB 27B6: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:54:57,326] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IPAD/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:54:59,642] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ID/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:01,968] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-fBOMB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:06,061] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-USDT 54c4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:08,894] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/FLOKI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:11,124] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DOLA/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:14,441] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MAI/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:22,908] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:25,606] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FIL/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:28,041] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MULTI/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:30,450] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/AST: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:35,001] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FIL/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:37,708] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-AVAX/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:40,284] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-stkBNB/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:42,912] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-dXCAD/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:48,182] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/stkBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:50,979] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:53,705] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:55:56,322] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-wUSDR/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:02,846] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MIX/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:05,539] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBTCB-ynBTCk CC09: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:08,767] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aPUFFER-WBNB 6b64: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:11,343] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:16,038] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:18,236] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BADAI/WBNB 1E90: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:20,749] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/dXCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:23,157] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBANK-WBNB D313: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:33,664] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FS/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:36,211] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/dXCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:38,624] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/dXCAD OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:41,495] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:46,070] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BUSD/SLM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:48,901] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:51,014] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/NFTB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:53,423] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BETS/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:56:58,053] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/TONCOIN: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:00,544] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-THE 3f3C: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:02,631] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-MATIC 1E3F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:05,040] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FS/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:07,496] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-FRAX/sFRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:12,864] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-USDT 2dA2: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:15,768] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT/USD+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:18,097] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/TAROT 8A8b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:20,433] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-wUSDR/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:24,327] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MIX/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:27,213] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FS/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:29,692] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FEAR/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:32,100] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-USDC fBF2: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:36,906] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSnBNB-WBNB 6708: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:40,489] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/USDT OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:43,079] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-jBRL/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:47,738] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aankrBNB-DUSD 87b1: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:50,564] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-TON 80F2: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:52,925] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-ERN 67D3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:57:55,622] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:01,206] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USD+/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:03,808] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IDIA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:06,348] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:08,540] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:13,413] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/LQDR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:15,985] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/BTCB OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:18,645] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:21,040] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-jBRL/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:26,821] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-40-THE CC08: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:30,106] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-43-THE 8423: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:33,463] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/KOL: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:38,911] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IDIA/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:41,722] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-qTHE/THE 2ffA: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:44,765] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:51,367] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-WBNB/BIFI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:54,173] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/ANKR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:57,128] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:58:59,819] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-THE/FLOKI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:04,400] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BTCB/multiBTC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:07,282] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-cpTHENA/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:09,838] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/PLAY: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:12,647] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PLAY/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:16,983] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:20,949] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/TAROT 7086: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:23,961] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/IPAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:28,260] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDV/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:30,700] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETH/pxETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:33,475] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-xZOOMER/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:35,914] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/TTM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:41,955] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-Cake/mCake: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:45,741] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT/USDa: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:48,115] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-axlLqdr/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:50,454] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-fBOMB/sliveThe: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:56,327] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/$AIAGENT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 01:59:58,969] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-31-THE 1Cb3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:01,853] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-35-THE 5736: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:04,811] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-41-THE CBDe: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:25,472] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCGPT-BUSD 68C0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:28,074] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFTM-WBNB 4Fee: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:30,517] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCGPT-BUSD 4536: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:33,018] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-RDNT 5420: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:42,398] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-FLOKI EF58: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:44,927] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-LQDR 3DCD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:47,315] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDOGE-WBNB F0cF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:49,743] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aOKSE-WBNB 1191: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:56,588] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-EDU da6F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:00:59,102] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDOGE-WBNB 3427: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:01,531] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aMULTI-WBNB 7103: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:03,964] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-ANKR b548: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:11,357] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aMULTI-WBNB D6f4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:14,153] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-ANKRETH 33e9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:17,586] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-ANKR 0808: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:20,187] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-OATH d561: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:25,224] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-ANKR C1be: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:28,193] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-FRXETH 0A4F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:31,815] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-USDT 3aBD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:38,965] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-FRXETH A888: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:41,733] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-XCAD A245: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:44,505] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aJBRL-USDC 6827: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:46,946] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-FRAX A59c: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:52,653] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-FRAX 759D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:56,221] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-WBNB 0F68: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:01:58,889] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-ANKRETH 63bd: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:03,075] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWUSDR-DOLA 0876: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:05,760] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSTKBNB-THE 27D7: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:08,040] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-BTE 5bc0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:10,566] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-BTE 221c: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:18,773] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-BTC 21B7: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:21,858] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-LINK 587A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:24,896] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-BTCB 7be8: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:27,853] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRAX-ERN 18ab: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:34,041] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-STKBNB 7ea9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:37,012] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-ERN 578A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:40,098] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aARKEN-WBNB 44D0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:42,544] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aEQB-WBNB B32f: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:51,861] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-OOE C8C3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:54,320] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aEQB-FRXETH B098: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:57,269] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aAXLLQDR-WBNB e1ce: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:02:59,602] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-STKBNB 0537: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:05,032] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aARKEN-WBNB 1780: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:07,600] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-USDT b297: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:10,142] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-WBNB e7a9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:12,998] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCSIX-USDT 9a14: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:19,953] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-WBNB 9cfd: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:22,747] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-RDNT cC00: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:25,720] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-USDV c409: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:28,120] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aOATH-ERN 75df: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:33,216] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aankrBNB-DUSD b1f9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:36,070] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-DUSD 88ab: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:38,465] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aOATH-ERN 2F85: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:41,185] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aankrBNB-XVS 2206: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:46,315] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-AST 11a9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:49,087] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSOL-WBNB eBFD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:51,438] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aTOKEN-WBNB d726: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:54,214] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-BTCB fc90: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:03:59,412] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-USDV 9FEf: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:02,300] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-inwbETH Be13: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:05,065] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-LISTA ff22: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:07,832] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aORBS-WBNB bA1A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:13,572] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-VINU 00d7: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:16,143] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aZRO-WBNB 98Eb: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:18,553] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-RWA 4aAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:20,921] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for ajCHF-USDC 4657: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:24,704] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-SDM 152E: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:27,058] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-8-THE a082: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:29,522] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-10-THE e1BD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:32,259] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-21-THE 7f08: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:37,977] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-44-THE Bc06: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:41,577] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 6055: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:43,950] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-26-THE 2c1f: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:46,345] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-28-THE 4C61: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:53,937] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare A2bB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:56,266] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 3E21: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:04:58,546] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 31eD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:05:00,913] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 638a: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:05:03,231] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare E25c: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:05:09,274] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 8996: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:05:11,987] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare f360: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-08-01 02:05:14,385] 	ERROR 	150 	bribe_data.py 	<module>() 	Error occurred during Bribe Data process. Error: Dataframe is empty
[2025-08-01 02:05:15,008] 	INFO 	17 	revenue_data.py 	<module>() 	Revenue Data Started
[2025-08-01 02:05:26,858] 	ERROR 	94 	revenue_data.py 	<module>() 	Error occurred during Revenue Data process. Error: 'int' object has no attribute 'startswith'
[2025-08-01 02:05:27,447] 	INFO 	16 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2025-08-01 02:05:34,483] 	ERROR 	96 	revenue_data_v2.py 	<module>() 	Error occurred during Revenue Data process. Error: 'float' object has no attribute 'startswith'
[2025-08-01 02:05:35,073] 	INFO 	29 	tvl_data.py 	<module>() 	TVL Data Started
[2025-08-01 02:05:35,239] 	INFO 	33 	tvl_data.py 	<module>() 	Response status code: 403
[2025-08-01 02:05:35,239] 	INFO 	34 	tvl_data.py 	<module>() 	Response content: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta nam
[2025-08-01 02:05:35,239] 	ERROR 	95 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tvl_data.py", line 35, in <module>
    ids_df = pd.json_normalize(response.json()['data'])[['symbol', 'type', 'address']]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-08-01 02:05:35,240] 	INFO 	108 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2025-08-01 02:05:35,348] 	ERROR 	182 	tvl_data.py 	<module>() 	Error occurred during TVL Data Fusion process. Error: name 'ids_df' is not defined
Traceback (most recent call last):
  File "tvl_data.py", line 115, in <module>
    ids_cl_df = ids_df[(ids_df['type'] != 'Volatile') & (ids_df['type'] != 'Stable')]
NameError: name 'ids_df' is not defined
[2025-08-01 02:05:35,348] 	INFO 	187 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2025-08-01 02:05:35,348] 	ERROR 	248 	tvl_data.py 	<module>() 	Error occurred during TVL Data Combined process. Error: name 'v1_df' is not defined
Traceback (most recent call last):
  File "tvl_data.py", line 190, in <module>
    tvl_df = pd.concat([v1_df, cl_df], ignore_index=True)
NameError: name 'v1_df' is not defined
[2025-08-01 02:05:36,078] 	INFO 	27 	fee_tvl_data.py 	<module>() 	Fee TVL Data Started
[2025-08-01 02:05:44,676] 	ERROR 	66 	fee_tvl_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-08-01 02:05:44,676] 	INFO 	77 	fee_tvl_data.py 	<module>() 	Fee TVL Data Ended
