[2025-07-01 01:22:30,407] 	INFO 	14 	id_data_v2.py 	<module>() 	ID Data Started
[2025-07-01 01:33:52,279] 	INFO 	163 	id_data_v2.py 	<module>() 	ID Data Ended
[2025-07-01 01:33:53,039] 	INFO 	14 	id_data_v3.py 	<module>() 	ID Data Started
[2025-07-01 01:33:53,351] 	ERROR 	44 	id_data_v3.py 	<module>() 	Error occurred during ID Data process. Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "id_data_v3.py", line 29, in <module>
    data = requests.get(url=fusion_api).json()['data']
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-07-01 01:33:53,938] 	INFO 	19 	day_data.py 	<module>() 	Day Data Started
[2025-07-01 01:33:57,459] 	ERROR 	69 	day_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-07-01 01:33:57,459] 	INFO 	80 	day_data.py 	<module>() 	Day Data Ended
[2025-07-01 01:33:57,459] 	INFO 	86 	day_data.py 	<module>() 	Day Data Fusion Started
[2025-07-01 01:34:00,800] 	ERROR 	145 	day_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-07-01 01:34:00,800] 	INFO 	156 	day_data.py 	<module>() 	Day Data Fusion Ended
[2025-07-01 01:34:00,801] 	INFO 	163 	day_data.py 	<module>() 	Day Data Combined Started
[2025-07-01 01:34:04,960] 	ERROR 	196 	day_data.py 	<module>() 	Data successfully added to Google Sheets.
[2025-07-01 01:34:04,960] 	INFO 	207 	day_data.py 	<module>() 	Day Data Combined Ended
[2025-07-01 01:34:05,792] 	INFO 	31 	pair_data.py 	<module>() 	Pair Data Started
[2025-07-01 01:35:11,456] 	ERROR 	108 	pair_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-07-01 01:35:11,456] 	INFO 	119 	pair_data.py 	<module>() 	Pair Data Ended
[2025-07-01 01:35:11,457] 	INFO 	136 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2025-07-01 01:35:11,743] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aynBNB-WBNB, Address: 0xCfac0990700eD9B67FeFBD4b26a79E426468a419, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:11,896] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: auniBTC-FBTC, Address: 0xe2BB11d6b6A39e55762F5e14D632F0981198b3A7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:12,012] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: auniBTC-BTCB, Address: 0x99Afd6Fa0Db50A60470437e28e666196018841ce, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:12,172] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:12,702] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aslpBNB-WBNB, Address: 0xda5BC174E3c122058Eb42465b78C7e1F639820A9, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:12,849] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: ajEUR-USDC, Address: 0x85B0533848E2a97069e2a5937fa927cA9133AF97, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:13,038] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: ajCHF-USDC, Address: 0x786C5B03C7A0a88A4cE6860a0D4aB2a1a0864e57, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:13,195] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aenzoBTC-ynBTCk, Address: 0x87BB1366C3d7AFc80bB0cEc7800FcE29D11AdBd7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:13,505] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:13,791] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:13,919] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:14,217] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:14,339] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-DOLA, Address: 0xdB6BfF81311C5C4F72668D9C4c8a5E2CB4584A82, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:15,597] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:15,864] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:15,994] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LPBNB, Address: 0x47600Bc3aE9b5b97ef92A55E550066944fE17670, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:16,230] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-ERN, Address: 0xc609daA86FF43F34Eef52C468CbC4934eF8D2502, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:16,365] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-EDU, Address: 0x4bD39cfb05545c4238316dA69eCadA1b4CaABC05, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:17,454] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-USDV, Address: 0x739e561786C920D025d57eD99be5D4EcA3458E3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:17,978] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:18,649] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:18,772] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-DUSD, Address: 0xCf4cf048d0c754A71d559296aC1ccc9aeb0b25Be, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:19,053] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDC-WUSDR, Address: 0xcbdE6C4f202eCc13267fD53913bc44B4Dd6eF998, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:19,761] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSOLV-WBNB, Address: 0xBB59e13bD9B6Bf6f3E0421939649Fd47927d2206, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:20,178] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSFRXETH-FRXETH, Address: 0xd9e98A73102391b3D7d1D94C0c58541aBf99a14F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:20,420] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aORBS-WBNB, Address: 0x130348553b3dEA5d65767Dc390eFF257F9a9181d, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:20,558] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aOATH-ERN, Address: 0xDF5751BBEf0241878852253F8541A02c3Cbc2dd1, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:21,389] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aJBRL-USDC, Address: 0xd63bBA6078a328b93758Cc7556e21D3380397D41, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:21,501] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aID-WBNB, Address: 0xB66566fD115CAf17633504A5165a319F17D9F096, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:22,118] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:22,229] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:22,654] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-WBETH, Address: 0x3bc0Fc25aD4456cdd4e4805ED89Ec0d80Db5e2c4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:22,786] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-RDNT, Address: 0x403e786B4168eC718E2e6cB4FA874aaDE73D54f0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:22,937] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:23,196] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFAIR3-WBNB, Address: 0x0293b7F6B245C0160d0da4ea3b936569EcE5740c, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:23,332] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-wstETH, Address: 0xFa71B01d2fE9337fEc17A7b5Af294F8Ef6040F3A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:23,451] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:23,796] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-USDV, Address: 0xBf5E6e3c88C88cF6b17327f57a61A3A997f13a3b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:24,055] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-STKBNB, Address: 0x8b41d72def3867E19f2285B45DA655e24928018F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:24,184] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-FRAX, Address: 0x82437aFe50B21d6910498706Dd4Fc7b6567e03eb, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:25,873] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:26,757] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-THE, Address: 0x1335Ffc90516b022425dBcFe4eA3610aA45f6C3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:27,002] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ETH, Address: 0x6B32E9178a6670dc9b19a74FE5080C54ea5347C7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:27,150] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:27,734] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aARKEN-WBNB, Address: 0xCB995DaE5238c1e08C7289b335c80ED8d129A46b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:28,786] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-BTCB, Address: 0xE6BB969eE786E1a42C179EB11A5038640304Cb4C, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:28,919] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-ANKRETH, Address: 0xa31FDaD356065d3E244Ac33C2e7901Fff7e8AAec, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:29,624] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-8-THE a082, Address: 0x8929E532E551c82f5736aa18C78440691BC542D9, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:31,126] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-36-THE Bc6a, Address: 0xFd60A2B164C86751Df65c8cf895F7b07e5A48C35, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:31,850] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-15-THE d198, Address: 0x7cEfCEa15158Df116534C75F2f677d4D1f077028, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:32,117] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-11-THE 2ff5, Address: 0xe1Ad12B9f713710a8FFF593eB1c6E5F82d3C0b3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:32,255] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare E25c, Address: 0x52ddB7BD7CA73a20b6334cC08fCACa9906992a15, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:32,513] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 638a, Address: 0xaB3790c5FaB8AFf0A41640Eb2c7b280289c657E5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:32,779] 	ERROR 	176 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 31eD, Address: 0x37CbdBb97C34ba577ADbFbB80b517cD6caB636E8, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2025-07-01 01:35:45,185] 	ERROR 	215 	pair_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-07-01 01:35:45,185] 	INFO 	226 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2025-07-01 01:35:45,185] 	INFO 	233 	pair_data.py 	<module>() 	Pair Data Combined Started
[2025-07-01 01:36:49,593] 	ERROR 	279 	pair_data.py 	<module>() 	Data successfully added to Google Sheets.
[2025-07-01 01:36:49,593] 	INFO 	290 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2025-07-01 01:36:50,521] 	INFO 	31 	bribe_data.py 	<module>() 	Bribe Data Started
[2025-07-01 01:36:54,118] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aID-WBNB 4666: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:36:56,974] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/dXCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:36:59,766] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-29-THE f060: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:02,649] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-BTCB 7be8: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:09,204] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETH/frxETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:12,869] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:16,075] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FRAX/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:22,662] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/ANKR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:26,047] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-11-THE 2ff5: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:28,855] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-FRAX 6e92: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:35,152] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-TAROT/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:38,223] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-jBRL/BRZ: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:41,365] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/FITFI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:44,092] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BUSD/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:52,270] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aMULTI-WBNB 7103: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:55,000] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-C98/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:37:58,224] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-DOLA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:01,024] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/XCAD OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:07,295] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MULTI/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:10,268] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:13,060] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDC/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:15,405] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-EDU da6F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:21,609] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:24,103] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETS Alpha/USD+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:27,339] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DAO/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:30,108] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aOATH-ERN 75df: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:35,795] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FRAX/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:38,740] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-USDT 54c4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:41,778] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FITFI/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:44,416] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BTCB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:51,697] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-XCAD A245: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:54,972] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/LINK: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:38:58,112] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:00,897] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MAI/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:07,345] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-DOLA/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:10,577] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:12,894] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DAI/MAI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:16,829] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/USD+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:24,869] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-DAO/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:27,690] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/ANKR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:30,931] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-THE C5be: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:34,093] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BTCB/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:39,918] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-FRAX/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:43,208] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:46,003] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-frxETH/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:53,086] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FITFI/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:56,060] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETH/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:39:58,855] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aLTC-WBNB 531d: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:01,735] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/ANKR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:07,118] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IPAD/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:10,114] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/CHAM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:13,278] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-JRT/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:15,957] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare Ea85: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:24,039] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:26,553] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-AVAX/CHAM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:29,607] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MAI/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:35,449] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 6055: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:38,254] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-CHAM/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:41,105] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aTWT-ANKRBNB B039: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:44,437] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-sfrxETH/frxETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:52,366] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aAITECH-WBNB E8d7: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:54,986] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FS/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:40:57,700] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrMATIC/MATIC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:00,747] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MAI/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:06,410] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-WBNB 9cfd: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:09,812] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/BIFI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:12,499] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDAO-ankrBNB 0fB0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:15,548] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-TAROT/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:27,598] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-NGL/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:30,421] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-AST 3459: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:33,093] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-DAO/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:35,819] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FIL/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:42,163] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-BTC 21B7: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:46,073] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/dXCAD OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:49,300] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-stkBNB/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:53,723] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MATIC/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:56,560] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/PRIMAL: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:41:59,375] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/dXCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:02,198] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/ankrETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:08,077] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/BTCB OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:11,460] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/LQDR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:14,236] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aynBNB-WBNB 32Fc: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:17,097] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:22,575] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-jBRL/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:25,533] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-DEUS 03CA: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:28,360] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-MAI/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:33,082] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/USDC OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:35,830] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/USDT OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:38,571] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BETS/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:41,339] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:47,384] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-FRXETH 0A4F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:51,467] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IDIA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:54,102] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 9287: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:42:56,834] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/LIQ: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:03,303] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-LIBERA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:06,331] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/LIBERA: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:09,517] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-WBNB/BIFI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:12,347] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/rBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:18,766] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-LIBERA/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:21,757] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aLISUSD-CHEEMS E491: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:25,254] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-FRAX/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:32,310] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/WBNB OLD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:35,022] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSINGULARRY-WBNB 9A37: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:37,684] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BTCB/XCAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:40,669] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-UNW/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:45,422] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:48,347] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:51,046] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-cpTHE/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:43:53,788] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BTCB/multiBTC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:00,382] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-LQDR/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:03,307] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-THE/FLOKI: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:06,049] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:08,399] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-cpTHE/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:14,413] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/stkBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:17,417] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-liveThe/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:20,280] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-ANKR b548: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:23,098] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-CHAM/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:28,568] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/DEUS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:31,362] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETS Alpha/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:34,096] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT+/USD+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:37,638] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/PLAY: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:43,599] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/PLAY: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:47,016] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-cpTHENA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:49,906] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DJED/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:52,630] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/MATIC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:44:57,920] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-DOGE/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:01,011] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PSTAKE/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:04,011] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/FTM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:06,837] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BUSD/SLM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:12,827] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MIX/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:15,414] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DOLA/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:18,864] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-MORE/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:21,516] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-WBNB/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:26,647] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/ankrETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:30,107] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-AVAX/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:33,192] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:35,565] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BUSD/SLM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:41,620] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/ankrMATIC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:44,924] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FS/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:47,636] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-OVN/USDT+: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:50,792] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DOLA/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:56,822] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-GHNY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:45:59,716] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/USDC-jCHF-120-vLP: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:02,405] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/MIX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:05,096] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aEQB-FRXETH B098: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:12,443] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDV/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:14,990] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/frxETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:18,350] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/BTCB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:21,352] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-LINK 587A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:27,841] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MIX/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:30,462] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MULTI/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:33,079] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IDIA/C98: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:36,127] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-22-THE 0053: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:43,516] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-MAI/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:47,665] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aGHNY-WBNB 8618: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:50,227] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USD+/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:52,755] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:46:58,013] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/TAROT 8A8b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:00,510] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-XCAD/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:03,078] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFTM-WBNB 4Fee: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:05,561] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/ETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:11,679] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSTKBNB-THE 27D7: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:14,433] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BTCB/GHNY: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:17,521] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/TONCOIN: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:20,553] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/BTCB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:26,514] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-fBOMB/liveThe: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:29,635] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BTCB/Bridged mBTC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:33,291] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-sUSDa/USDa: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:42,192] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDV/USDC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:45,068] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-fBOMB/sliveThe: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:48,114] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDT/USDa: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:50,768] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-axlLqdr/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:56,194] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BTCB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:47:58,913] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PION/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:01,500] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/LIQ: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:04,562] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BADAI/WBNB 1E90: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:10,315] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-DUSD/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:13,974] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-WBNB 755b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:16,580] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBTCB-WBNB 4D3F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:19,184] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-WBNB 9555: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:25,502] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-WBNB e947: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:28,505] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBTCB-WBNB A7f0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:31,221] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-RDNT 97e8: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:34,667] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-WBNB 8e3A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:40,905] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-WBNB 7677: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:44,376] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/PLAY: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:47,373] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCGPT-BUSD 4536: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:50,109] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-RDNT 6f46: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:48:58,047] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aGHNY-WBNB f892: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:00,827] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWUSDR-USDC aa92: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:03,826] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ABOND/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:06,472] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-FLOKI EF58: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:12,717] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IDIA/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:15,530] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-USDT 3e64: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:18,164] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-USDT 6071: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:20,840] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-USDC fBF2: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:25,210] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aGRAIN-WBNB EAD0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:27,902] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-THE 1Ef3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:30,211] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aXCAD-WBNB f2BC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:33,125] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aXCAD-WBNB 376F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:38,819] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDOGE-WBNB 3427: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:41,642] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aOKSE-WBNB 1191: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:44,287] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDOGE-WBNB F0cF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:46,886] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aTWT-WBNB 5196: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:53,090] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-MPX/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:55,882] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HAY/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:49:58,530] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aOKSE-WBNB B4B4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:01,182] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aDAO-BUSD 988B: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:09,068] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-ANKRETH 33e9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:12,682] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-ANKR 0808: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:15,335] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aXCAD-BUSD 3613: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:18,030] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSFRXETH-FRXETH 2C3A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:24,517] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-FRXETH 275E: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:27,924] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-FRAX A59c: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:31,316] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aJBRL-USDC 6827: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:33,973] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-ANKR eE80: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:40,738] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-THE 1A05: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:44,137] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aLTC-WBNB 0C62: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:46,938] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-RBNB 5772: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:50,180] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aJBRL-USDC 00FC: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:56,502] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-FRXETH A888: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:50:59,819] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSTKBNB-THE 78AF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:02,531] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-WBNB 0252: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:05,284] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-WBETH 308D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:12,444] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-BTE 221c: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:15,476] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/SEF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:18,465] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWUSDR-DOLA 0876: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:23,477] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-LQDR 0D12: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:26,513] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-ETH 2e3d: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:30,114] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aLVL-WBNB E6EE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:32,918] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-ERN 578A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:46,778] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-ETH D728: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:50,465] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-STKBNB 0537: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:53,524] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aARKEN-WBNB 44D0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:51:56,237] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFIL-ANKRBNB 356A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:03,355] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-PENDLE 76c9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:06,308] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBTCB-STKBNB F31F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:09,546] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBTCB-STKBNB 51b5: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:16,191] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aARKEN-WBNB 1780: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:18,930] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aAXLLQDR-WBNB Aa30: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:21,790] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aID-ANKRBNB 32c6: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:24,899] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aEQB-WBNB B32f: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:33,101] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aEQB-WBNB 982b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:36,036] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-OOE 1974: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:38,807] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCSIX-USDT 9a14: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:41,556] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aCSIX-USDT 458D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:47,732] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRXETH-RDNT a427: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:51,794] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aPNP-WBNB C4FF: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:54,518] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-USDV c409: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:52:57,284] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aHAY-FRAX 759D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:06,318] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDC-WUSDR 9891: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:09,237] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aOATH-ERN 2F85: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:12,328] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for astERN-ERN d9F9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:18,731] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-PLAY 5430: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:21,611] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aankrBNB-XVS 2206: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:25,083] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aankrBNB-DUSD b1f9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:28,255] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-ERN f047: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:38,812] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-PLAY B74d: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:41,640] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSOL-WBNB eBFD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:44,296] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-AST 11a9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:47,112] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HBR/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:53,942] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-FRAX 1070: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:53:57,799] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-BTCB fc90: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:00,918] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aTOKEN-WBNB d726: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:05,933] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-wstETH bEcD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:09,260] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWEETH-ETH 0D39: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:12,596] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-XVS eE7D: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:15,301] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-LISTA ff22: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:22,495] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aZRO-WBNB 98Eb: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:25,413] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-COCO effD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:28,222] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for auniBTC-BTCB 5E0a: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:31,470] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for auniBTC-FBTC e40b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:39,983] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aUSDT-FDUSD C4F3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:42,979] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-RWA 4aAD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:45,825] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aynBNBx-WBNB 7e0F: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:48,576] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aORBS-WBNB bA1A: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:54,334] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aMONKY-WBNB Cd00: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:54:57,334] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-BLOCK 5DD2: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:00,257] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBTCB-ynBTCk CC09: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:05,853] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-SDM 152E: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:08,897] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aKILO-WBNB 5aFa: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:11,636] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-6-THE BA13: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:14,392] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-HBR/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:20,638] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWoD-WBNB 00B1: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:23,470] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aenzoBTC-ynBTCk Af96: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:26,556] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFAIR3-WBNB 8D29: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:29,236] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-BR CddB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:35,428] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-17-THE Fc8C: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:39,055] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-12-THE 2367: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:41,923] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-14-THE B802: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:44,638] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-15-THE d198: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:51,006] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-16-THE D6c9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:54,167] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-10-THE e1BD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:57,158] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-13-THE Dbe6: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:55:59,747] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDV/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:05,074] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-24-THE 9302: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:08,256] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-23-THE c02E: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:10,955] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-26-THE 2c1f: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:13,728] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-27-THE fEa0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:20,322] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-35-THE 5736: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:23,501] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-33-THE 025d: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:26,829] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/HBR: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:33,249] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-37-THE F310: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:36,640] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-30-THE e5c9: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:39,438] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-31-THE 1Cb3: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:42,662] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 6613: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:47,899] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-44-THE Bc06: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:52,350] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-45-THE 1B9C: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:56:56,361] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-41-THE CBDe: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:04,175] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-42-THE d5bb: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:08,354] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-40-THE CC08: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:12,087] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare E25c: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:17,570] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare A2bB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:20,557] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 3E21: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:23,196] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare a32e: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:25,921] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 31eD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:32,354] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 8996: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:35,625] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-xZOOMER/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:38,304] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare f117: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:41,080] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-FRAX/CUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:47,329] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare a373: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:49,943] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-IDIA/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:52,730] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDC/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:57:55,090] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-eTHENA/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:01,650] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-fBOMB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:04,483] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-Bridged mwBETH/wBETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:08,887] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-FIL/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:14,108] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-DAO/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:17,099] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/SLM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:19,847] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ankrBNB/FXS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:26,602] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-jBRL/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:29,569] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-BNBx/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:33,419] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-GRAIN/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:36,179] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-CGPT/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:42,551] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-WBNB/NFTB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:45,410] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/FRAX: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:49,437] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-QUO/USDT: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:52,207] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-HAY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:58:57,574] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFTM-WBNB 6e6B: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:00,520] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-ETH/pxETH: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:03,624] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-CaptainBNB/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:06,314] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PERRY/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:12,357] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-USDV 9FEf: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:15,579] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aSnBNB-WBNB 6708: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:19,177] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aMULTI-WBNB D6f4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:23,701] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-EDU 6feA: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:26,715] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aETH-XCAD 7Fcf: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:29,805] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-LPBNB Ba2b: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:32,522] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare f360: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:38,762] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aFRAX-ERN 18ab: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:43,373] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aANKRBNB-USDT b297: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:46,128] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aAXLLQDR-WBNB e1ce: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:52,520] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aankrBNB-DUSD 87b1: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:55,873] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-39-THE EB04: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 01:59:58,685] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-7-THE deb0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:01,765] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-19-THE 6683: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:08,513] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-43-THE 8423: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:12,079] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aWBNB-KOMA 78E4: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:14,591] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for IV-9-THE 3fd0: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:17,047] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aBNBX-BTC 5f88: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:24,919] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for DEShare 50e8: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:27,906] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-PRIMAL/BUSD: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:30,375] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/TAROT 7086: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:33,282] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for asolvBTC-BTCB 0995: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:40,360] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-qTHE/THE 2ffA: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:43,256] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-qTHE/QUO: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:46,120] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-USDT/TTM: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:48,586] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-Cake/mCake: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:56,004] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-USDC/THE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:00:58,379] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for vAMM-ETH/JARVIS: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:01:01,366] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-BKN/WBNB: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:01:03,957] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for sAMM-mPendle/PENDLE: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:01:11,738] 	ERROR 	78 	bribe_data.py 	<module>() 	Error occurred while fetching bribes from https://binance.llamarpc.com for aGRAIN-WBNB 6BC7: 429 Client Error: Too Many Requests for url: https://binance.llamarpc.com/
[2025-07-01 02:01:14,374] 	ERROR 	150 	bribe_data.py 	<module>() 	Error occurred during Bribe Data process. Error: Dataframe is empty
[2025-07-01 02:01:14,973] 	INFO 	17 	revenue_data.py 	<module>() 	Revenue Data Started
[2025-07-01 02:01:26,246] 	ERROR 	94 	revenue_data.py 	<module>() 	Error occurred during Revenue Data process. Error: 'int' object has no attribute 'startswith'
[2025-07-01 02:01:26,829] 	INFO 	16 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2025-07-01 02:01:33,887] 	ERROR 	96 	revenue_data_v2.py 	<module>() 	Error occurred during Revenue Data process. Error: 'float' object has no attribute 'startswith'
[2025-07-01 02:01:34,466] 	INFO 	29 	tvl_data.py 	<module>() 	TVL Data Started
[2025-07-01 02:01:34,586] 	INFO 	33 	tvl_data.py 	<module>() 	Response status code: 403
[2025-07-01 02:01:34,586] 	INFO 	34 	tvl_data.py 	<module>() 	Response content: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta nam
[2025-07-01 02:01:34,586] 	ERROR 	95 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tvl_data.py", line 35, in <module>
    ids_df = pd.json_normalize(response.json()['data'])[['symbol', 'type', 'address']]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-07-01 02:01:34,587] 	INFO 	108 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2025-07-01 02:01:34,629] 	ERROR 	182 	tvl_data.py 	<module>() 	Error occurred during TVL Data Fusion process. Error: name 'ids_df' is not defined
Traceback (most recent call last):
  File "tvl_data.py", line 115, in <module>
    ids_cl_df = ids_df[(ids_df['type'] != 'Volatile') & (ids_df['type'] != 'Stable')]
NameError: name 'ids_df' is not defined
[2025-07-01 02:01:34,629] 	INFO 	187 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2025-07-01 02:01:34,629] 	ERROR 	248 	tvl_data.py 	<module>() 	Error occurred during TVL Data Combined process. Error: name 'v1_df' is not defined
Traceback (most recent call last):
  File "tvl_data.py", line 190, in <module>
    tvl_df = pd.concat([v1_df, cl_df], ignore_index=True)
NameError: name 'v1_df' is not defined
[2025-07-01 02:01:35,359] 	INFO 	27 	fee_tvl_data.py 	<module>() 	Fee TVL Data Started
[2025-07-01 02:01:44,137] 	ERROR 	66 	fee_tvl_data.py 	<module>() 	Data successfully appended to Google Sheets.
[2025-07-01 02:01:44,137] 	INFO 	77 	fee_tvl_data.py 	<module>() 	Fee TVL Data Ended
