[2023-02-09 00:55:57,193] 	INFO 	28 	pair_data.py 	<module>() 	ID Data Started
[2023-02-09 00:56:23,839] 	INFO 	56 	pair_data.py 	<module>() 	ID Data Ended
[2023-02-09 00:56:23,839] 	INFO 	59 	pair_data.py 	<module>() 	Pair Data Started
[2023-02-09 00:56:44,294] 	ERROR 	78 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: 'date'
[2023-02-09 00:56:49,039] 	INFO 	131 	pair_data.py 	<module>() 	Pair Data Ended
[2023-02-09 01:11:36,147] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-02-09 01:11:39,087] 	INFO 	60 	day_data.py 	<module>() 	Day Data Ended
[2023-02-09 02:19:34,515] 	INFO 	28 	pair_data.py 	<module>() 	ID Data Started
[2023-02-09 02:19:54,563] 	INFO 	56 	pair_data.py 	<module>() 	ID Data Ended
[2023-02-09 02:19:54,563] 	INFO 	59 	pair_data.py 	<module>() 	Pair Data Started
[2023-02-09 02:20:14,919] 	ERROR 	78 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: 'date'
[2023-02-09 02:20:19,504] 	INFO 	131 	pair_data.py 	<module>() 	Pair Data Ended
[2023-02-09 02:46:40,551] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-02-09 02:46:43,061] 	INFO 	60 	day_data.py 	<module>() 	Day Data Ended
[2023-02-09 03:14:45,008] 	INFO 	28 	pair_data.py 	<module>() 	ID Data Started
[2023-02-09 03:15:06,267] 	INFO 	56 	pair_data.py 	<module>() 	ID Data Ended
[2023-02-09 03:15:06,267] 	INFO 	59 	pair_data.py 	<module>() 	Pair Data Started
[2023-02-09 03:15:27,137] 	ERROR 	78 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: 'date'
[2023-02-09 03:15:31,938] 	INFO 	131 	pair_data.py 	<module>() 	Pair Data Ended
[2023-02-09 03:17:57,046] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-02-09 03:17:59,013] 	INFO 	60 	day_data.py 	<module>() 	Day Data Ended
[2023-02-09 04:13:11,986] 	INFO 	28 	pair_data.py 	<module>() 	ID Data Started
[2023-02-09 04:14:04,460] 	INFO 	56 	pair_data.py 	<module>() 	ID Data Ended
[2023-02-09 04:14:04,460] 	INFO 	59 	pair_data.py 	<module>() 	Pair Data Started
[2023-02-09 04:14:22,137] 	ERROR 	78 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: 'date'
[2023-02-09 04:14:26,251] 	INFO 	131 	pair_data.py 	<module>() 	Pair Data Ended
[2023-02-09 04:17:30,624] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-02-09 04:17:33,229] 	INFO 	60 	day_data.py 	<module>() 	Day Data Ended
[2023-02-09 05:10:42,114] 	INFO 	28 	pair_data.py 	<module>() 	ID Data Started
[2023-02-09 05:11:34,946] 	INFO 	56 	pair_data.py 	<module>() 	ID Data Ended
[2023-02-09 05:11:34,946] 	INFO 	59 	pair_data.py 	<module>() 	Pair Data Started
[2023-02-09 05:11:53,475] 	ERROR 	78 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: 'date'
[2023-02-09 05:11:56,588] 	INFO 	131 	pair_data.py 	<module>() 	Pair Data Ended
[2023-02-09 05:13:39,026] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-02-09 05:13:41,735] 	INFO 	60 	day_data.py 	<module>() 	Day Data Ended
[2023-02-09 06:15:12,783] 	INFO 	28 	pair_data.py 	<module>() 	ID Data Started
[2023-02-09 06:15:50,430] 	INFO 	56 	pair_data.py 	<module>() 	ID Data Ended
[2023-02-09 06:15:50,430] 	INFO 	59 	pair_data.py 	<module>() 	Pair Data Started
[2023-02-09 06:16:09,258] 	ERROR 	78 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: 'date'
[2023-02-09 06:16:14,610] 	INFO 	131 	pair_data.py 	<module>() 	Pair Data Ended
[2023-02-09 06:19:36,459] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-02-09 06:19:38,947] 	INFO 	60 	day_data.py 	<module>() 	Day Data Ended
[2023-02-09 07:10:46,700] 	INFO 	28 	pair_data.py 	<module>() 	ID Data Started
[2023-02-09 07:11:06,493] 	INFO 	56 	pair_data.py 	<module>() 	ID Data Ended
[2023-02-09 07:11:06,493] 	INFO 	59 	pair_data.py 	<module>() 	Pair Data Started
[2023-02-09 07:11:27,292] 	ERROR 	78 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: 'date'
[2023-02-09 07:11:32,924] 	INFO 	131 	pair_data.py 	<module>() 	Pair Data Ended
[2023-02-09 07:13:34,029] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-02-09 07:13:36,713] 	INFO 	60 	day_data.py 	<module>() 	Day Data Ended
[2023-02-09 08:14:24,664] 	INFO 	28 	pair_data.py 	<module>() 	ID Data Started
[2023-02-09 08:14:41,299] 	INFO 	56 	pair_data.py 	<module>() 	ID Data Ended
[2023-02-09 08:14:41,299] 	INFO 	59 	pair_data.py 	<module>() 	Pair Data Started
[2023-02-09 08:15:02,123] 	ERROR 	78 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: 'date'
[2023-02-09 08:15:07,247] 	INFO 	131 	pair_data.py 	<module>() 	Pair Data Ended
[2023-02-09 08:18:42,952] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-02-09 08:18:44,585] 	INFO 	60 	day_data.py 	<module>() 	Day Data Ended
[2023-02-09 09:11:25,330] 	INFO 	28 	pair_data.py 	<module>() 	ID Data Started
[2023-02-09 09:11:44,475] 	INFO 	56 	pair_data.py 	<module>() 	ID Data Ended
[2023-02-09 09:11:44,475] 	INFO 	59 	pair_data.py 	<module>() 	Pair Data Started
[2023-02-09 09:12:03,553] 	ERROR 	78 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: 'date'
[2023-02-09 09:12:08,124] 	INFO 	131 	pair_data.py 	<module>() 	Pair Data Ended
[2023-02-09 09:14:42,291] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-02-09 09:14:44,933] 	INFO 	60 	day_data.py 	<module>() 	Day Data Ended
[2023-02-09 10:11:21,837] 	INFO 	28 	pair_data.py 	<module>() 	ID Data Started
[2023-02-09 10:11:34,480] 	INFO 	56 	pair_data.py 	<module>() 	ID Data Ended
[2023-02-09 10:11:34,480] 	INFO 	59 	pair_data.py 	<module>() 	Pair Data Started
[2023-02-09 10:11:54,665] 	ERROR 	78 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: 'date'
[2023-02-09 10:11:59,175] 	INFO 	131 	pair_data.py 	<module>() 	Pair Data Ended
