[2023-02-09 00:55:57,193] 	INFO 	28 	pair_data.py 	<module>() 	ID Data Started
[2023-02-09 00:56:23,839] 	INFO 	56 	pair_data.py 	<module>() 	ID Data Ended
[2023-02-09 00:56:23,839] 	INFO 	59 	pair_data.py 	<module>() 	Pair Data Started
[2023-02-09 00:56:44,294] 	ERROR 	78 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: 'date'
[2023-02-09 00:56:49,039] 	INFO 	131 	pair_data.py 	<module>() 	Pair Data Ended
[2023-02-09 01:11:36,147] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2023-02-09 01:11:39,087] 	INFO 	60 	day_data.py 	<module>() 	Day Data Ended
